MyFirstMVCApp/Controllers/EmployeesController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MyFirstMVCApp.Models;

namespace MyFirstMVCApp.Controllers
{
    public class EmployeesController : Controller
    {
        public static List<Employees> empRecord = new List<Employees>();

        public IActionResult Index()
        {

            //by default these items will be shown everytime when the page is loaded
            if (empRecord.Count == 0)
            {
                empRecord.Add(new Employees { Id = 1, Name = "Ankur", City = "Malmö" });
                empRecord.Add(new Employees { Id = 2, Name = "Rahul", City = "Lund" });
            }

            return View(empRecord);
        }

        //this is to load the create page for input
       // GET:Default/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST:Default/Create
        [HttpPost]
        public IActionResult Create(Employees e)
        {
            empRecord.Add(e);
            return RedirectToAction("Index");
        }

        // GET:Default/Details
        public IActionResult Details(int Id, Employees e)
        {
            e = empRecord.Find(x => x.Id == e.Id);


            return View(e);
        }

        // GET:Default/Edit
        public IActionResult Edit(int? Id, Employees e)
        {
            e = empRecord.Find(x => x.Id == e.Id);


            return View(e);
        }

        //POST:Default/Edit
        [HttpPost]
        public IActionResult Edit(Employees e)
        {
            if (ModelState.IsValid)
            {
                var temp = empRecord.Find(x => x.Id == e.Id);
                empRecord.Remove(temp);
                empRecord.Add(e);
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");


        }

        //GET: Default/Delete
        public IActionResult Delete(int? Id, Employees e)
        {
            e = empRecord.Find(x => x.Id == e.Id);
            empRecord.Remove(e);


            return View(e);
        }


    }
}

MyFirstMVCApp/Controllers/FeverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFirstMVCApp.Models;
namespace MyFirstMVCApp.Controllers
{
    public class FeverController : Controller
    {
        public IActionResult Index()
        {
           
                return View();
        }

        [HttpPost]
        public ActionResult Index(Temperature t)
        {
            String _user = "Arwa";
            HttpContext.Session.SetString("User", _user);
            ViewBag.Name = HttpContext.Session.GetString("User");

            if (t.TNumber > 37)
            {
                ViewBag.Message = "you have fever";
                return View(t);
            }
            else
            {
                ViewBag.Message = "You have no fever";
                return View(t);
            }

        }
    }

   


}

MyFirstMVCApp/Controllers/GuessingGameController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFirstMVCApp.Models;



namespace MyFirstMVCApp.Controllers
{
    public class GuessingGameController : Controller
    {

       //create a variable 
        String _user = "Arwa";

        //create a random for every session
        Random _randNum = new Random();

        //create static variable for attempts made
        static int guess = 0;

       
        
        [HttpGet]
        public ActionResult Index()
        {

            
            //add string variable in your session
            HttpContext.Session.SetString("User", _user);
            ViewBag.Name = HttpContext.Session.GetString("User");

            //add random number in session
            int n = _randNum.Next(0, 101);
            HttpContext.Session.SetInt32("RandNum", n);
            ViewBag.Num = HttpContext.Session.GetString("RandNum");

            return View();



        }



        [HttpPost]
        public IActionResult GuessNumber()
        {
            
            string result;
            string result1;
            string result2;
            string result3;


          
            //loop the maximum tries as i which is not more than 5
            if(guess < 5)
            {

                //retrieve the number from input textbox
                int num1 = Convert.ToInt32(HttpContext.Request.Form["txtFirst"].ToString());
                guess++;
            
                //check if the number is higher than the session random number
                if (num1 < HttpContext.Session.GetInt32("RandNum"))
                {
                    //guess++;
                    result = "guesses:" + " " + guess;
                    result1 = "Go higher";
                    result2 = "the random number was:" + " " + HttpContext.Session.GetInt32("RandNum");

                    ViewBag.SumResult = result.ToString();
                    ViewBag.SumResult1 = result1.ToString();
                    ViewBag.SumResult2 = result2.ToString();

                    return View("index");




                }
               
                //check if the number is lower than the session random number
                else if (num1 > HttpContext.Session.GetInt32("RandNum"))
                {
                    result = "guesses:" + " " + guess;
                    result1 = "Go lower";
                    result2 = "the random number was:" + " " + HttpContext.Session.GetInt32("RandNum");

                    ViewBag.SumResult = result.ToString();
                    ViewBag.SumResult1 = result1.ToString();
                    ViewBag.SumResult2 = result2.ToString();

                    return View("index");


                }
               
                //check if the number is equal to session random number
                else if (num1 == HttpContext.Session.GetInt32("RandNum"))
                {
                   
                    result = "guesses:" + " " + guess;
                    result1 = "congratulations!";
                    result2 = "the random number was:" + " " + HttpContext.Session.GetInt32("RandNum");

                    ViewBag.SumResult = result.ToString();
                    ViewBag.SumResult1 = result1.ToString();
                    ViewBag.SumResult2 = result2.ToString();

                    return View("index");

                }
               


            }
           

            return View("Index");


        }

        










        ////ViewBag.Message("You have" + (allowedTries - numberOfTries), "tries left. Enter another number:");





    }
        }
    



        
  










  



     

MyFirstMVCApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstMVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Arwa Lokat</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>@*end col-lg-8*@
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Fever" asp-action="Index">Fever</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="GuessingGame" asp-action="Index">Guessing the Number</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employee Records</a>
                            </li>
                            
                        </ul>
                    </div>
                
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - MyFirstMVCApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MyFirstMVCApp/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstMVCApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Arwa Lokat</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

              
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GuessingGame" asp-action="Index">Guessing NumberGame</a>
                        </li>

                    </ul>
                </div>

            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                
                    @RenderBody()
                
            </main>

        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - MyFirstMVCApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>